package codigo;

import java_cup.runtime.Symbol;

parser code {:
    private Symbol s;

    public void syntax_error(Symbol s) {
        this.s = s;
    }
    
    public Symbol getS() {
        return this.s;
    }
:};

terminal
    IF,
    Parentesis_a,
    Parentesis_c,
    P_coma,
    Identificador,
    Numero,
    TRUE,
    FALSE,
    Igual_Igual,
    Menor,
    Menor_Igual,
    Mayor,
    Mayor_Igual,
    ERROR;


non terminal S,I, C, O, V;

start with S;
S ::= S I | I;

I ::= IF Parentesis_a C Parentesis_c P_coma;

C ::= Identificador O V;

O ::= Igual_Igual | Menor | Menor_Igual | Mayor | Mayor_Igual;

V ::= Numero | TRUE | FALSE;
